name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
        igo: [yaegi, ssa, gomacro, igo]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -tags ${{ matrix.igo }} -v ./...
